SELECT TOP (1000) [SALESDOCUMENT]
      ,[LASTCHANGEDATE]
      ,[LASTCHANGEDATETIME]
      ,[SALESORGANIZATION]
      ,[DISTRIBUTIONCHANNEL]
      ,[ORGANIZATIONDIVISION]
      ,[PURCHASEORDERBYCUSTOMER]
      
  FROM [dbo].[S4HSalesOrders]